/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "moaljwszyvgynoydhvif"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vYWxqd3N6eXZneW5veWRodmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5MzY4NzAsImV4cCI6MjA5MTUxMjg3MH0.BAAZcRm8Is0nGWuk-SkX-8tSszPrmlUpPgWFuzNpQHw"